"""add orders public_id and json columns

Revision ID: 82513317fea2
Revises: a90ff066090f
Create Date: 2026-02-08 21:32:00.748488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82513317fea2'
down_revision: Union[str, Sequence[str], None] = 'a90ff066090f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('public_id', sa.String(), nullable=True))
    op.add_column('orders', sa.Column('customer_json', sa.Text(), nullable=True))
    op.add_column('orders', sa.Column('items_json', sa.Text(), nullable=True))
    op.create_index(op.f('ix_orders_public_id'), 'orders', ['public_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_public_id'), table_name='orders')
    op.drop_column('orders', 'items_json')
    op.drop_column('orders', 'customer_json')
    op.drop_column('orders', 'public_id')
    # ### end Alembic commands ###
